# Generated by Django 5.1 on 2024-10-06 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('employees', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('conclusions', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('survey_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_level', models.CharField(max_length=255)),
                ('program_goal_understanding', models.CharField(max_length=255)),
                ('role_understanding', models.CharField(max_length=255)),
                ('supervisor_support', models.CharField(max_length=255)),
                ('program_encouragement', models.CharField(max_length=255)),
                ('program_impact', models.CharField(max_length=255)),
                ('interaction_assessment', models.CharField(max_length=255)),
                ('program_priority', models.CharField(max_length=255)),
                ('program_information', models.CharField(max_length=255)),
                ('knowledge_application', models.CharField(max_length=255)),
                ('program_expectations', models.CharField(max_length=255)),
                ('program_obstacles', models.CharField(max_length=255)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.enterprise')),
            ],
        ),
    ]
